services:
  ${IMAGE_NAME}-${ENV_NAME}:
    image: ${IMAGE_NAME}:${BUILD_ID}
    restart: unless-stopped
     labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${IMAGE_NAME}-${ENV_NAME}.rule=Host(`${TRAEFIK_HOST}`) && PathPrefix(`${TRAEFIK_PATH}`)"
      - "traefik.http.services.${IMAGE_NAME}-${ENV_NAME}.loadbalancer.server.port=80"
    networks:
      - ${NETWORK}

networks:
  ${NETWORK}:
    external: true